library(ArchR)
library(stringr)
library(ggplot2)
library(dplyr)
library(glue)
library(parallel)
library(ggpubr)
library(Seurat)
library(SeuratDisk)
library(GenomicRanges)
library(HDF5Array)
library(SummarizedExperiment)
library(Signac)

addArchRThreads(threads = 20) 

proj2 <- loadArchRProject('/home/ah2428/project/PTSD_ATAC/proj2')
mat2 <- getMatrixFromProject(proj2,useMatrix='GeneScoreMatrix',threads=1)
saveHDF5SummarizedExperiment(mat2,'/home/ah2428/project/PTSD_ATAC/proj2/mat2')
