library(ArchR)
library(stringr)
library(ggplot2)
library(dplyr)
library(glue)
library(parallel)
library(ggpubr)
library(Seurat)
library(SeuratDisk)
library(GenomicRanges)
library(HDF5Array)
library(SummarizedExperiment)
library(Signac)

addArchRThreads(threads = 20) 

proj1 <- loadArchRProject('/home/ah2428/project/PTSD_ATAC/proj1')
mat1 <- getMatrixFromProject(proj1,useMatrix='GeneScoreMatrix',threads=1)
saveHDF5SummarizedExperiment(mat1,'/home/ah2428/project/PTSD_ATAC/proj1/mat1')
